spring.application.name=nhom3
server.port=8080

# Đã sửa thành localhost chỉ vào máy của bạn
# spring.datasource.url=jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=schoolmanager
# spring.datasource.username=sa
# spring.datasource.password=123123
# Sửa localhost thành địa chỉ Server Hosting
spring.datasource.url=jdbc:sqlserver://SQL1002.site4now.net:1433;databaseName=db_ac9082_studentdb;encrypt=true;trustServerCertificate=true
spring.datasource.username=db_ac9082_studentdb_admin
spring.datasource.password=0865371356Az
# Ép kiểu dữ liệu khi gửi từ Java sang SQL Server là Unicode
spring.datasource.connection-properties=SendStringParametersAsUnicode=true
spring.thymeleaf.cache=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Hiển thị log SQL trên console để tiện theo dõi và debug
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
# Ép toàn bộ phản hồi HTTP trả về định dạng UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

# Cấu hình cho Thymeleaf (nếu bạn có dùng render trực tiếp)
spring.thymeleaf.encoding=UTF-8
spring.messages.encoding=UTF-8
# ==========================================
# CẤU HÌNH JWT (JSON WEB TOKEN)
# ==========================================
# Chuỗi bí mật (Secret Key) để ký token (Yêu cầu ít nhất 256-bit / 32 ký tự)
jwt.secret=DayLaChuoiBiMatSieuCapVoDichCuaDuAnHRManagement2026!@#
# Thời gian sống của Token (tính bằng mili giây, ví dụ 86400000 = 24 giờ)
jwt.expiration=86400000

# ==========================================
# CẤU HÌNH GỬI EMAIL (Sử dụng Gmail)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.username=ngocdt3102@gmail.com
# Mật khẩu ứng dụng (App Password) của Gmail, KHÔNG phải mật khẩu đăng nhập bình thường
spring.mail.password=cach qmeq tceg rwsp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true